# common configuration file

# Path parameters
[Path]
#home directory
tbot_home = "/project/bots/tbot_report/"
logs_dir = "logs/"
dev_conf = "config/config_devel.toml"
test_conf = "config/config_test.toml"
prod_conf = "config/config_prod.toml"

# Logging settings
[Logging]
# The output format for the messages printed to the console
# See https://docs.python.org/3/library/logging.html#logrecord-attributes for information about the {}-attributes
format = "{asctime} | {threadName} | {name} | {message}"
# Logging level: ignore all log entries with a level lower than the specified one
# Valid options are FATAL, ERROR, WARNING, INFO, and DEBUG
level = "DEBUG"
